services:
  api_scorepal:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: api_scorepal
    networks:
      - web
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - web
    ports:
      - "3306:3306"
    volumes:
      - ./Server/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    ports:
      - "8082:80"
    networks:
      - web

networks:
  web:
    external: true
