services:
  api_vamosvamos:
    build:
      context: ./VamosVamosServer
      dockerfile: Dockerfile
    container_name: api_vamosvamos
    networks:
      - web
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=VamosVamos

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - web
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    ports:
      - "8082:80"
    networks:
      - web

networks:
  web:
    external: true
