services:
  # Ton serveur principal
  vamosvamosserver:
    build:
      context: ./VamosVamosServer
      dockerfile: Dockerfile
    container_name: api
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
    networks:
      - web
    depends_on:
      - db
    ports:
      - "8080:8080"

  reverse-proxy:
    image: traefik:v2.9
    container_name: reverse-proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.myresolver.acme.email=sacha.laurent71@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - web

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: "172.18.0.2"
    ports:
      - "8082:80"

networks:
  web:
    external: true