name: Update README on master

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: pip install -r Workflow/requirements.txt

      - name: Build Docker image for API
        run: docker build -t scorepal .

      - name: Run Docker container
        run: |
            docker run -d --name scorepal_container -p 8080:80 scorepal

      - name: Wait for API to be ready
        run: |
          echo "⏳ Waiting for the API to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/swagger/v1/swagger.json > /dev/null; then
              echo "✅ API is up!"
              break
            fi
            sleep 2
          done

      - name: Run update_readme.py
        run: python Workflow/update_readme.py

      - name: Stop container
        run: docker stop scorepal_container && docker rm scorepal_container
